name: zeytin
description: A server app using the shelf package and Docker.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.10.4

dependencies:
  crypto: ^3.0.7
  dio: ^5.9.1
  encrypt: ^5.0.3
  mime: ^2.0.0
  path: ^1.9.1
  shelf: ^1.4.2
  shelf_multipart: ^2.0.1
  shelf_router: ^1.1.2
  shelf_static: ^1.1.3
  shelf_web_socket: ^3.0.0
  uuid: ^4.5.2
  dart_jsonwebtoken: ^2.7.1
  web_socket_channel: ^3.0.3

dev_dependencies:
  http: ^1.2.2
  lints: ^6.0.0
  test: ^1.25.6
