name: zeytin
description: A server solution that is independent of external dependencies, has its own database engine, is end-to-end encrypted, and is autonomous.
version: 2.1.0
license: AGPL-3.0
repository: https://github.com/JeaFrid/Zeytin

environment:
  sdk: ^3.10.4

dependencies:
  crypto: ^3.0.7
  dio: ^5.9.1
  encrypt: ^5.0.3
  mime: ^2.0.0
  path: ^1.9.1
  shelf: ^1.4.2
  shelf_multipart: ^2.0.1
  shelf_router: ^1.1.2
  shelf_static: ^1.1.3
  shelf_web_socket: ^3.0.0
  uuid: ^4.5.2
  dart_jsonwebtoken: ^2.7.1
  archive: ^4.0.7

dev_dependencies:
  http: ^1.2.2
  lints: ^6.0.0
  test: ^1.25.6
